# 缺失值处理

# 重复值处理

# 异常值处理

# 字符串处理

# 标准化与归一化

In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

StandardScaler().fit_transform(X=X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [2]:
from sklearn.preprocessing import Normalizer

Normalizer().fit_transform(X_train)

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

# 类别属性处理

In [3]:
import pandas as pd

X = [['male', 4, 10],
     ['female', 20, 3], ]
df = pd.DataFrame(X, columns=['sex', 'location', 'web'])
df

sex  location  web
0    male         4   10
1  female        20    3

In [4]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()
enc.fit(df.loc[:,['sex']])
new = enc.transform(df.loc[:,['sex']]).toarray()

new

array([[0., 1.],
       [1., 0.]])

In [7]:
from sklearn.compose import ColumnTransformer

num_attribs = ['location', 'web']
cat_attribs = ["sex"]

full_pipeline = ColumnTransformer([
        ("cat", OneHotEncoder(), cat_attribs),
    ], remainder='passthrough')
df_prepared = full_pipeline.fit_transform(df)

df_prepared

array([[ 0.,  1.,  4., 10.],
       [ 1.,  0., 20.,  3.]])